[2023-09-01 10:09:41,816 root CRITICAL] Exception:Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 6c9c02ab84836d0f787531a911a89f403b21b6b8 (server)
[2023-09-01 10:09:41,817 root CRITICAL] Traceback (most recent call last):
   File "esxcli.py", line 431, in HandleCmdline
   File "esxcli.py", line 384, in _HandleOneCmd
   File "esxcli.py", line 949, in _ParseCLIArgs
   File "esxcli.py", line 927, in _RaiseCLIParseException
 CLIParseException: <unprintable CLIParseException object>
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/Session.py", line 857, in Login
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/Session.py", line 1010, in _GetServiceContent
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 557, in <lambda>
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/VmomiSupport.py", line 363, in _InvokeMethod
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1306, in InvokeMethod
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1391, in GetConnection
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 960, in _VerifyThumbprint
 pyVmomi.SoapAdapter.ThumbprintMismatchException: Server has wrong SHA1 thumbprint: fakefakefakefakefakefakefakefakefakefake (required) != 6c9c02ab84836d0f787531a911a89f403b21b6b8 (server)

[2023-09-01 10:09:59,227 root CRITICAL] Exception:Invalid SHA1 thumbprint -- THUMBPRINT
[2023-09-01 10:09:59,238 root CRITICAL] Traceback (most recent call last):
   File "esxcli.py", line 431, in HandleCmdline
   File "esxcli.py", line 384, in _HandleOneCmd
   File "esxcli.py", line 949, in _ParseCLIArgs
   File "esxcli.py", line 927, in _RaiseCLIParseException
 CLIParseException: <unprintable CLIParseException object>
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/Session.py", line 811, in Login
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1208, in __init__
 Exception: Invalid SHA1 thumbprint -- THUMBPRINT

[2023-09-01 10:10:14,742 root CRITICAL] Exception:Invalid SHA1 thumbprint -- THUMBPRINT
[2023-09-01 10:10:14,748 root CRITICAL] Traceback (most recent call last):
   File "esxcli.py", line 431, in HandleCmdline
   File "esxcli.py", line 384, in _HandleOneCmd
   File "esxcli.py", line 949, in _ParseCLIArgs
   File "esxcli.py", line 927, in _RaiseCLIParseException
 CLIParseException: <unprintable CLIParseException object>
 
During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/Session.py", line 811, in Login
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1208, in __init__
 Exception: Invalid SHA1 thumbprint -- THUMBPRINT

[2023-09-01 10:20:04,357 root CRITICAL] Exception:Invalid SHA1 thumbprint -- THUMBPRINT
[2023-09-01 10:20:04,360 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/Session.py", line 811, in Login
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1208, in __init__
 Exception: Invalid SHA1 thumbprint -- THUMBPRINT

[2023-09-01 10:20:19,367 root CRITICAL] Exception:Invalid SHA1 thumbprint -- THUMBPRINT
[2023-09-01 10:20:19,398 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/Session.py", line 811, in Login
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1208, in __init__
 Exception: Invalid SHA1 thumbprint -- THUMBPRINT

[2023-09-01 10:20:27,115 root CRITICAL] Exception:Invalid SHA1 thumbprint -- THUMBPRINT
[2023-09-01 10:20:27,115 root CRITICAL] Traceback (most recent call last):
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/Session.py", line 811, in Login
   File "/build/mts/release/bora-13004787/bora/build/esxcli/release/build/pyVmomi/SoapAdapter.py", line 1208, in __init__
 Exception: Invalid SHA1 thumbprint -- THUMBPRINT

